config/routes.rb
RaceCalendar::Application.routes.draw do
  resources :races do
    get 'list', on: :collection, as: :list
    get 'inactive', on: :collection, as: :inactive
  end

  resources :classifieds

  resources :classified_messages, only: :create

  namespace 'admin' do
    resources :races, only: [:edit, :update, :destroy] do
      get 'activate', action: :activate
    end
  end

  resource :dashboard, only: :show

  get '/sign_in', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  resource :sessions, only: [:new, :create]

  namespace :api do
    resources :races, only: [:create, :index]
  end

  if defined?(Raddocs)
    mount Raddocs::App => "/docs"
  end

  root 'races#index'
end

app/models/race.rb
class Race < ActiveRecord::Base
  geocoded_by :full_address
  validate :new_race, on: :create
  validates :email, :date, :title, presence: true
  before_save :generate_token, on: :create

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }
  scope :same_day, ->(date) { where(date: date) }

  def full_address
    [street, city, state, zip, country].compact.reject(&:blank?).join(', ')
  end

  def activate!
    coords = geocode
    self.latitude = coords.try(:first)
    self.longitude = coords.try(:last)
    self.active = true
    self.save
  end

  private

  def new_race
    errors.add(:title, "already exists") if
    Race.same_day(date).where("UPPER(title) LIKE UPPER(?)", "%#{title}%").present?
  end

  def generate_token
    self.token = SecureRandom.hex.upcase
  end
end

app/controllers/admin/races_controller.rb
class Admin::RacesController < ApplicationController
  before_filter :require_user
  respond_to :html

  def edit
    @race = Race.find(params[:id])
  end

  def update
    @race = Race.find(params[:id])
    @race.update_attributes(race_params)
    respond_with @race, location: :dashboard
  end

  def activate
    race = Race.find(params[:race_id])
    race.activate!
    RaceMailer.activated(race).deliver
    flash[:success] = "Succesfully activated race #{race.title}"
    redirect_to :dashboard
  end

  def destroy
    race = Race.find(params[:id])
    flash[:success] = "Succesfully removed race #{race.title}"
    race.destroy
    redirect_to :list_races
  end

  protected

  def race_params
    params.require(:race).permit(
      :title, :date, :street, :city, :state,
      :country, :zip, :url, :description, :email
    )
  end
end

app/controllers/api/races_controller.rb
class Api::RacesController < ApiController

  def create
    race = Race.new(race_params)
    if race.save
      render json: race, status: :created, serializer: Api::RaceSerializer
    else
      render json: {errors: race.errors.full_messages}, status: :bad_request
    end
  end

  def index
    render json: Race.active.where(:date => Chronic.parse(start_date)..Chronic.parse(end_date)).
      order(:date), each_serializer: Api::RaceSerializer
  end

  protected

  def start_date
    params[:start_date].presence || Date.today
  end

  def end_date
    params[:end_date].presence || (start_date + 1.year)
  end

  def race_params
    params.require(:race).permit(
      :title,
      :city,
      :state,
      :country,
      :url,
      :latitude,
      :longitude,
      :email
    ).merge({ date: Chronic.parse(params[:race][:date]) })
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  respond_to :html

  after_filter :set_session_dates

  expose(:start_date) do
    date_parse(params[:start_date]) || session[:start_date].try(:[], :value).try(:to_date) || Date.today.to_date
  end
  expose(:end_date) do
    date_parse(params[:end_date]) || session[:end_date].try(:[], :value).try(:to_date) || 1.year.from_now.to_date
  end

  def index
    @races = races_hash
  end

  def new
    @race = Race.new
  end

  def create
    @race = Race.new(race_params)
    flash[:success] = "Your race has been submitted for approval. This usually happens within 24 hours" if @race.save
    respond_with @race, location: :list_races
  end

  def list
    @races = races.order(:date).group_by(&:date)
  end

  def edit
    @race = Race.find_by!(token: params[:id])
  end

  def update
    @race = Race.find_by(token: params[:id])
    @race.update_attributes(race_params)
    respond_with @race, location: :list_races
  end

  def destroy
    race = Race.find_by(token: params[:id])
    flash[:success] = "Succesfully removed race #{race.title}" if race.destroy
    redirect_to :list_races
  end

  protected

  def races_hash
    Gmaps4rails.build_markers(races.group_by(&:latitude)) do |races, marker|
      marker.lat races[1][0].latitude
      marker.lng races[1][0].longitude
      marker.infowindow render_to_string partial: '/races/race', locals: { races: races }
    end
  end

  def date_parse(date)
    date.values.join('/').try(:to_date) if date
  end

  def races
    Race.active.where(:date => start_date..end_date.end_of_month)
  end

  def set_session_dates
    session[:start_date] = {value: start_date.strftime('%Y-%m-%d'), expires: 1.minute.from_now}
    session[:end_date] = {value: end_date.strftime('%Y-%m-%d'), expires: 1.minute.from_now}
  end

  def race_params
    params.require(:race).permit(
      :title, :date, :street, :city, :state,
      :country, :zip, :url, :description, :email
    )
  end
end

app/views/races/_form.html.haml
%dl
  %dt= f.label :title, "Race Name"
  %dd= f.text_field :title, autofocus: 'autofocus'

%dl
  %dt= f.label :date
  %dd= f.date_select :date

%dl
  %dt= f.label :street
  %dd= f.text_field :street

%dl
  %dt= f.label :city
  %dd= f.text_field :city

%dl
  %dt= f.label :state
  %dd= f.text_field :state

%dl
  %dt= f.label :country
  %dd= f.text_field :country

%dl
  %dt= f.label :zip, "ZIP"
  %dd= f.text_field :zip

%dl
  %dt= f.label :url, "Website"
  %dd= f.text_field :url

%dl
  %dt= f.label :description
  %dd= f.text_area :description

%dl
  %dt= f.label :email
  %dd= f.text_field :email

app/views/races/_race.html.haml
- races.second.each do |race|
  %ul
    %li= race.title
    %li= link_to race.url, race.url, target: "_blank"
    %li= race.date.strftime("%b %d, %Y")
  ___________

app/views/races/_race_table.html.haml
%table.race
  %thead
    %tr
      - ["Name", "Address"].each do |th|
        %th= th
      - if current_user
        %th
  %tbody
    - races.each do |race_hash|
      %tr.date
        %td{colspan: 2}= race_hash.first.strftime("%b %d, %Y")

      - race_hash.second.sort_by{ |r| r.title}.each do |race|
        %tr
          %td= link_to(race.title, race.url, target: "_blank")
          %td= link_to(race.full_address, race.url, target: "_blank")
          - if current_user
            %td= link_to("Edit Race", edit_admin_race_path(race))

app/views/races/edit.html.haml
= form_for @race, url: race_path(id: @race.token) do |f|
  = render 'form', f: f
  = f.submit "Update Race"

%ul
  %li
    = link_to "Delete Race", race_path(id: @race.token), method: :delete, data: { confirm: "Are you sure you want to delete this race?" }

app/views/races/index.html.haml
= form_tag races_path, method: :get do
  %fieldset
    Show races from the beginning of
    = date_select 'start_date', 'start_date', {default: start_date, discard_day: true, order: [:month, :year]}
    to the end of
    = date_select 'end_date', 'end_date', {default: end_date, discard_day: true, order: [:month, :year]}
    %input(type="submit" value="Filter")

#map(style='width: 1020px; height: 500px;')

:javascript
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {
  zoom: 3,
  center: new google.maps.LatLng(39.5, -98.35)
  }, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(#{raw @races.to_json});
    handler.fitMapToBounds();
  });

app/views/races/list.html.haml
= form_tag list_races_path, method: :get do
  %fieldset
    Show races from the beginning of
    = date_select 'start_date', 'start_date', {default: start_date, discard_day: true, order: [:month, :year]}
    to the end of
    = date_select 'end_date', 'end_date', {default: end_date, discard_day: true, order: [:month, :year]}
    %input(type="submit" value="Filter")

= render 'race_table', races: @races

app/views/races/new.html.haml
= form_for @race do |f|
  = render 'form', f: f
  = f.submit "Create Race"