config/routes.rb
RaceCalendar::Application.routes.draw do
  resources :races do
    get 'list', on: :collection, as: :list
    get 'inactive', on: :collection, as: :inactive
  end

  resources :classifieds

  resources :classified_messages, only: :create

  namespace 'admin' do
    resources :races, only: [:edit, :update, :destroy] do
      get 'activate', action: :activate
    end
  end

  resource :dashboard, only: :show

  get '/sign_in', to: 'sessions#new'
  get '/sign_out', to: 'sessions#destroy'
  resource :sessions, only: [:new, :create]

  namespace :api do
    resources :races, only: [:create, :index]
  end

  if defined?(Raddocs)
    mount Raddocs::App => "/docs"
  end

  root 'races#index'
end

app/models/classified.rb
class Classified < ActiveRecord::Base
  validates :title, :price, :email, presence: true
  before_save :generate_token, on: :create

  def full_address
    [city, state, country].compact.reject(&:blank?).join(', ')
  end

  protected

  def generate_token
    self.token = SecureRandom.hex.upcase
  end
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  respond_to :html
  expose(:classifieds) { Classified.order(created_at: :desc) }

  def new
    @classified = Classified.new
  end

  def create
    @classified = Classified.new(classified_params)
    if @classified.save
      flash[:success] = "Succesfully added #{@classified.title}. You should receive an email containing a link to update or remove your classified"
      ClassifiedMailer.new_classified(@classified).deliver
    end
    respond_with @classified, location: :classifieds
  end

  def show
    @classified = Classified.find(params[:id])
    @classified_message = ClassifiedMessage.new
  end

  def edit
    @classified = Classified.find_by!(token: params[:id])
  end

  def update
    @classified = Classified.find_by!(token: params[:id])
    @classified.update_attributes(classified_params)
    respond_with @classified, location: :classifieds
  end

  def destroy
    classified = Classified.find_by!(token: params[:id])
    flash[:success] = "Succesfully removed classified #{classified.title}" if classified.destroy
    redirect_to :classifieds
  end

  protected

  def classified_params
    params.require(:classified).permit(
      :title, :description, :price, :city, :state,
      :country, :email, :filepicker_url
    )
  end
end

app/views/classifieds/_form.html.haml
%dl
  %dt= f.label :title
  %dd= f.text_field :title, autofocus: 'autofocus'

%dl
  %dt= f.label :description
  %dd= f.text_area :description

%dl
  %dt= f.label :price
  %dd= f.text_field :price

%dl
  %dt= f.label :city
  %dd= f.text_field :city

%dl
  %dt= f.label :state
  %dd= f.text_field :state

%dl
  %dt= f.label :country
  %dd= f.text_field :country

%dl
  %dt= f.label :email
  %dd= f.email_field :email

%dl
  %dt= f.label :filepicker_url, "Image"
  %dd= f.filepicker_field :filepicker_url

app/views/classifieds/_message_form.html.haml
= form_for @classified_message do |f|
  = f.hidden_field :classified_id, value: @classified.id
  %fieldset
    Contact the Seller:
    %dl
      %dt= f.label :name
      %dd= f.text_field :name

      %dt= f.label :email, "Email Address"
      %dd= f.email_field :email

      %dt= f.label :message
      %dd= f.text_area :message, rows: 8, cols: 40
    = f.submit "Send"
.sent_message
  %p Your message was sent successfully to the seller.

app/views/classifieds/edit.html.haml
= content_for :head do
  = filepicker_js_include_tag

= form_for @classified, url: classified_path(id: @classified.token) do |f|
  = render 'form', f: f
  = f.submit "Update Classified"

%ul
  %li
    = link_to "Delete Classified", classified_path(id: @classified.token), method: :delete, data: { confirm: "Are you sure you want to delete this classified?" }

app/views/classifieds/index.html.haml
=link_to "Add a Classified", :new_classified

%table.race
  %thead
    %tr
      - ["Title", "Price", "Location"].each do |th|
        %th= th
  %tbody
    - classifieds.each do |classified|
      %tr
        %td= link_to(classified.title, classified_path(classified))
        %td= link_to(classified.price, classified_path(classified))
        %td= link_to(classified.full_address, classified_path(classified))

app/views/classifieds/new.html.haml
= content_for :head do
  = filepicker_js_include_tag

= form_for @classified do |f|
  = render 'form', f: f
  = f.submit "Create Classified"

app/views/classifieds/show.html.haml
%dl
  %dt Title:
  %dd= @classified.title

%dl
  %dt Price:
  %dd= @classified.price

%dl
  %dt Description:
  %dd= @classified.description

%dl
  %dt Location:
  %dd= @classified.full_address

%dl
  %dt Image
  %dd= filepicker_image_tag @classified.filepicker_url, w: 600, h: 600, fit: 'clip'

= render 'message_form'